### ISSUE TITLE
Raidrive disconnects drive when RDP session disconnected

### ISSUE THREAD

**Issue by edrock200** [RaiDrive/Translation#108]
Thanks for the great product. Just installed it but it seems to drop mounts when I disconnect (not log off) from RDP from the machine that has Raidrive installed. Is this expected behavior?

**Comment by Stanly5** [comment]
@edrock200,
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~
