### ISSUE TITLE
Not Saving Custom Icon Option

### ISSUE THREAD

**Issue by sturoy71** [RaiDrive/Translation#109]
Whenever you close down the app, It always defaults to turning the "Use Custom Icon For Connected Drive" next time you start the app.

**Comment by Stanly5** [comment]
@sturoy71
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~
