### ISSUE TITLE
The login label at right corner can't be localized

### ISSUE THREAD

**Issue by SadPencil** [RaiDrive/Translation#113]
See the picture here: https://imghostr.com/8a8BGwAO
The language of my computer is set to Simplified Chinese.
RaiDrive 1.7.0
The login label at right corner displays as `登入`, which is the Traditional Chinese word. However the corresponding translation file have already been corrected several months ago.
Even if I load the localization file manually, the word doesn't change, no matter what localization file is selected.

**Comment by SadPencil** [comment]
Note: there is no such word as `登入` at `StringDictionary.zh-Hans.xaml` file. So where does this word come out from?

**Comment by SadPencil** [comment]
If I switch the language to other language, like korean, and the text of login label is set to a korean word. Then I switch back to Simplified Chinese, but the text of login label remains to be korean. It seems that the translation file need to be updated to fit the version 1.7.0.

**Comment by SadPencil** [comment]
I decompiled the RaiDrive 1.7.0 exe file and found that there are 190 items in the official Korean language. But the ` StringDictionary.ko.xaml` file here on the GitHub only contains 168 items. The xaml file should be definitely updated.

**Comment by Stanly5** [comment]
@SadPencil 
Thank you so much for this.
As you mentioned, v.1.7.0 has several new added lines on language files, and it was uploaded to get your helps to translation as well, even it was done by translation application. Please review and confirm it is good enough or not.
Have a great day~
