### ISSUE TITLE
Delegation aborted

### ISSUE THREAD

**Issue by eevleevs** [RaiDrive/Translation#122]
Occurs on 1.8.0 while trying to connect to Google Drive.

![image](https://user-images.githubusercontent.com/5012744/63266013-42e61e80-c28f-11e9-9df0-75e474a31fa5.png)

**Comment by Stanly5** [comment]
@eevleevs,
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://with.raidrive.com/session/sso

Thank you.
Have a nice day~

**Comment by eevleevs** [comment]
Followed up on https://with.raidrive.com/t/re-delegation-aborted/466
