### ISSUE TITLE
Could add new function, access other shared folder on google drive?

### ISSUE THREAD

**Issue by Hulen** [RaiDrive/Translation#13]
Could add new function, access other shared folder on google drive?

**Comment by Stanly5** [comment]
@Hulen 
Can you please tell me more to understand in detail what is your inquiry?

**Comment by Hulen** [comment]
Like AirExplorer, I can see other's people drives shared with me.

![image](https://user-images.githubusercontent.com/2930690/43366405-38959252-9370-11e8-9d25-f9bd5a80b45c.png)

**Comment by Stanly5** [comment]
@Hulen 
I conveyed this.
However could you please leave this message to RaiDrive Webpage again for better communication and log?
https://www.raidrive.com/contact/
