### ISSUE TITLE
Raidrive locked after windows update

### ISSUE THREAD

**Issue by wolfcheng** [RaiDrive/Translation#187]
![photo_2020-03-19_14-02-18](https://user-images.githubusercontent.com/22702724/77036736-bfd6a380-69ea-11ea-96fc-efb802094e62.jpg)

**Comment by Stanly5** [comment]
@wolfcheng 
I'm sorry for the inconvenience, but this is only for translation of RaiDrive, so can support technical things.
Could you please leave this message to https://with.raidrive.com to get the feedback from engineering team? 
Thank you and have a good day~

**Comment by wolfcheng** [comment]
The problem is solved
