### ISSUE TITLE
make it available for windows server 2016

### ISSUE THREAD

**Issue by shadowzentral** [RaiDrive/Translation#25]
i need to transfer bigger files to dropbox but it fails while installing.

**Comment by Stanly5** [comment]
Hello shadowzentral,
Here is only for the translation of RaiDrive, so proper person who can answer for your inquiry can not follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day!

**Comment by warsix4** [comment]
I am also experiencing this issue. Contacting RaiDrive on their website is totally ineffective. There is never a response. I've tried.

This issue prevents me from using the application at all.

**Comment by Stanly5** [comment]
@warsix4
If you got inconvenience from no response, sorry for that, might be missed it.
Here Github is only for the translation, but as far as I hear Professional version of RaiDrive which is not free would support Windows server and working on this to release.
