### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by GrandMasterX3** [RaiDrive/Translation#26]
Hi, thanks for your reply to my email the other day. It's sad that we gotta wait for amazon cloud API. I believe (as per your README) that you don't have any translation for Spanish yet. I wanted to help. Spanish is my mother tongue, and although some words like IP are maintained in Spanish, I did my best to maintain a windows-like vocabulary. There are some words that may require some work (depending on the context) but it should all be very understandable and clear.
[StringDictionary.txt](https://github.com/RaiDrive/Translation/files/2317151/StringDictionary.txt)

**Comment by Stanly5** [comment]
Hi,
Thank you so much for your interests and contribution.
Of course I can apply your translation files, but we'd like to keep the history for the update and also who is the contributor. Therefore could you please use "Pull Request" procedure in GitHub?
If you are not familiar with this, please follow below step.

- In [RaiDrive/Translation](https://github.com/RaiDrive/Translation) repository, click "Fork" which is upper right. It make the clone of RaiDrive/Translation in your page.
- In your GrandMasterX3/translation repository, choose "<>Code" tab. (upper left)
- Change the name of your translated file from StringDictionary.txt to StringDictionary.es.xaml.
- Click "Upload files"
- Upload the file with dragging your local "StringDictionary.es.xaml" file to the area, writing comments on the box just below "Commit changes", and then press the green "Commit changes" button.
- You can confirm everything is well on StringDictionary.es.xaml with click the file.
- For the pull request, choose"Pull requests" tab (just right side of <>Code), and press the green "New pull request" button.
- GitHub automatically checks what's the difference, and will show 1 changed file which is StringDictionary.es.xaml. Please double check base fork:RaiDrive/Translation master, <- head fork: GrandMasterX3/translation master. And then press the green "Create pull request".
- Writing the title and comments, and then press the green "Create pull request" button.

After above step, I can get your pull request, and after merge your pull request, it will be applied main file on RaiDrive Translation repository, and you are registered on our contributors.
Even it is a little bit troublesome you think, please follow our guidance. If you have any problem to do it, please leave a message.
Thank you so much for your contribution again!

**Comment by GrandMasterX3** [comment]
Hi again, I believe I did what you asked. Let me know if it is ok. I'm sorry that I'm new to GitHub 👌  Someday I'll be a good computer scientist 👍

**Comment by Stanly5** [comment]
Hi~ 
Thank you so much for your working! Your pull request was merged.
You can see the contributors for this translation repository and you are on that as well.

**Comment by GrandMasterX3** [comment]
Thanks. I believe the last update is pretty great. I think that it doesn't need any more changes for now. If you get to add more texts I'll definitely try to translate them, but for now, I think it's pretty solid and all Spanish speaking users should be able to enjoy the software without issues. If anyone finds a good suggestion I'll make sure to apply it.

**Comment by Stanly5** [comment]
Thank you so much for your great contribution!
Please keep watching our working and I would ask you some helps for the Spanish translation if you are ok.
