### ISSUE TITLE
Does not keep G-Drive authorization token after reboot

### ISSUE THREAD

**Issue by jcmarchi** [RaiDrive/Translation#32]
For Google Drive, each time the connection is closed (after disconnection, system reboot, exit application, etc), a new authorization is requested. Why doesn't RaiDrive keep the authorization token so it can simply re-login to G-Drive without re-authorizing every single time?

**Comment by jcmarchi** [comment]
Sorry. I just notice this Repo is only for the translation of the application. 
But, how can I report bugs and issues?

**Comment by Stanly5** [comment]
Yes, here is only for the translation of RaiDrive, so proper person who can answer for your inquiry can not follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day!

**Comment by jcmarchi** [comment]
Thanks.
