### ISSUE TITLE
RaiDrive  is not supported to onedriver of edu account 

### ISSUE THREAD

**Issue by zuoakang** [RaiDrive/Translation#35]
### The delegation has been canceled.
AADSTS65005: Using application 'RaiDrive' is currently not supported for your organization xxxx.edu.cn because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of xxxx.edu.cn before the application RaiDrive can be provisioned.

what should I do？

**Comment by Stanly5** [comment]
@zuoakang 
Here is only for the translation of RaiDrive.
For the fast supporting, please leave a message in RaiDrive website, https://raidrive.com/contact so that proper support team can know about it. I'm sorry for this.
Thanks a lot.

**Comment by zuoakang** [comment]
@Stanly5 thanks, I have already submitted this question in [https://raidrive.com/contact](https://raidrive.com/contact )

**Comment by gclinux** [comment]
I have the same error

**Comment by fuxiao567** [comment]
I have the same error

**Comment by Stanly5** [comment]
@gclinux 
Here is only for the translation of RaiDrive.
For the fast supporting, please leave a message in RaiDrive website, https://raidrive.com/contact so that proper support team can know about it. I'm sorry for this.
Thanks a lot.

**Comment by Stanly5** [comment]
@gclinux
Here is only for the translation of RaiDrive.
For the fast supporting, please leave a message in RaiDrive website, https://with.raidrive.com so that proper support team can know about it. I'm sorry for this.
Thanks a lot.

**Comment by Stanly5** [comment]
@gclinux
I'm sorry for sending the same message for several times, there was an error on the link. I hope you get the right place to get the answer shortly.

Here is only for the translation of RaiDrive.
For the fast supporting, please leave a message in RaiDrive website, https://with.raidrive.com  so that proper support team can know about it. I'm sorry for this.
Thanks a lot.
