### ISSUE TITLE
system.security.cryptography.X509Certificates error

### ISSUE THREAD

**Issue by forpw2009** [RaiDrive/Translation#38]
when i use onedrive cloud, always has this error , system.security.cryptography.X509Certificates,
could you tell me how to deal with it ?

**Comment by Stanly5** [comment]
Here GitHub is only for the translation of RaiDrive, so proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day!
