### ISSUE TITLE
Russian Translation improvement

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/Translation#43]
There is different suggestion for Russian translation as below.
Please leave a comment which one is better.
[StringDictionary.ru.zip](https://github.com/RaiDrive/Translation/files/2473638/StringDictionary.ru.zip)

**Comment by kostefun** [comment]
minor fixes, ok

**Comment by Stanly5** [comment]
@kostefun 
Thank you so much for your advice. I will apply it.
