### ISSUE TITLE
Doesn't remember login credentials

### ISSUE THREAD

**Issue by M0d3rn15t** [RaiDrive/Translation#47]
I was quite excited by this software initially. The problem of multiple Dropbox accounts along with the possible issues of low disk space solved by mapping online storage to PC drives.

Totally useless though because you have to login to the cloud storage every time you reboot. Totally ruins the utility of this product.

**Comment by Stanly5** [comment]
Here GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
