### ISSUE TITLE
RaiDrive adds "username@" in front of FTPS address

### ISSUE THREAD

**Issue by junglized** [RaiDrive/Translation#50]
Dear developers,

I know this is not related to translations but I couldn't find any support email addresses on your website.

I tried to add FTPS connection to my Qnap NAS drive I've got at home. I set up DDNS service on myqnapcloud.com. I chose device name "device", username "user" and ftps port "1234". So my cloud link is "device.myqnapcloud.com". RaiDrive puts "user@" at the beginning of the cloud link address making itself not able to connect to FTP. So basically instead of "ftps://device.myqnapcloud.com:1234" there is "ftps://user@device.myqnapcloud.com:1234". Could you please tell RaiDrive not to do that and let users put it themselves if necessary?

A few words more: I tried that with Total Commander. It didn't work with "user@" being added at the front of the address, when I removed it, it worked perfectly.

Best regards.

**Comment by Stanly5** [comment]
Hello~ 
As you mentioned, here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage. 
https://www.raidrive.com/contact/

Thank you~
Have a great day

**Comment by junglized** [comment]
Ah, fair enough. Sorry for trouble.
