### ISSUE TITLE
Translation from English into Italian

### ISSUE THREAD

**Issue by gabrig11** [RaiDrive/Translation#51]
Hi, I wanted to help you in the translation .....
You did a great job

`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:RaiDrive.Center.Languages" xmlns:system="clr-namespace:System;assembly=mscorlib">

	
	<system:String x:Key="Current.Language">it</system:String>

	<system:String x:Key="Settings">Impostazioni</system:String>
	<system:String x:Key="Settings.Header">Impostazioni</system:String>
	<system:String x:Key="Settings.General">Generale</system:String>
	<system:String x:Key="Settings.Language">Lingua</system:String>
	<system:String x:Key="Settings.Update">Aggiornamenti</system:String>
	<system:String x:Key="Settings.Facebook">Facebook</system:String>
	<system:String x:Key="Settings.Facebook.Like">Like</system:String>
	<system:String x:Key="Settings.TemporaryPath">Temporaneo</system:String>
	<system:String x:Key="Settings.Default">Default</system:String>
	<system:String x:Key="Settings.License">License</system:String>
	<system:String x:Key="Settings.Proxy">Proxy</system:String>

	<system:String x:Key="Settings.General.RunAtBoot">Avvia automaticamente quando si avvia Windows</system:String>
	<system:String x:Key="Settings.General.RunAtConnect">Avvia File Explorer quando viene connesso un drive</system:String>

	<system:String x:Key="Notice">Avviso</system:String>
	<system:String x:Key="AddDrive">Aggiungi</system:String>
	<system:String x:Key="AddDrive.Header">Nuovo drive</system:String>
	<system:String x:Key="AddDrive.Storage">Salvataggio</system:String>

	
	<system:String x:Key="AddDrive.Drive">Drive</system:String>

	
	<system:String x:Key="AddDrive.Network">Rete</system:String>
	<system:String x:Key="AddDrive.ReadOnly">Sola-lettura</system:String>
	<system:String x:Key="AddDrive.MountAtBoot">Riconnetti all'accesso</system:String>
	<system:String x:Key="AddDrive.AuthAtConnect">Connetti utilizzando credenziali diverse</system:String>
	<system:String x:Key="AddDrive.Account">Account</system:String>
	<system:String x:Key="AddDrive.Username">Username</system:String>
	<system:String x:Key="AddDrive.Password">Password</system:String>
	<system:String x:Key="AddDrive.Anonymous">Anonimo</system:String>
	<system:String x:Key="AddDrive.Address">Indirizzo</system:String>
	<system:String x:Key="AddDrive.Port">Porta</system:String>
	<system:String x:Key="AddDrive.Device">Dispositivo</system:String>
	<system:String x:Key="AddDrive.PrivateKey">Chiave privata</system:String>
	<system:String x:Key="AddDrive.Charset">Charset</system:String>
	<system:String x:Key="AddDrive.TransferMode">Modalità di trasferimento</system:String>
	<system:String x:Key="AddDrive.Encryption">Crittografia</system:String>

	<system:String x:Key="Vailidation.Volume">Si prega di inserire un'etichetta di volume valida</system:String>
	<system:String x:Key="Vailidation.VolumeExist">Questo nome esiste già</system:String>
	<system:String x:Key="Vailidation.VolumeInvalidChar">Un'etichetta del volume non può contenere nessuno dei seguenti caratteri:</system:String>
	<system:String x:Key="Vailidation.VolumeInvalidStr">Non utilizzare i seguenti nomi riservati:</system:String>
	<system:String x:Key="Vailidation.Letter">Si prega di selezionare una lettera di unità non assegnata</system:String>
	<system:String x:Key="Vailidation.Address">Si prega di inserire un hostname oppure un indirizzo IP</system:String>
	<system:String x:Key="Vailidation.Address.WebDAV">Si prega di inserire un URL</system:String>
	<system:String x:Key="Vailidation.Address.LocalDrive">Si prega di selezionare una cartella del suo PC</system:String>
	<system:String x:Key="Vailidation.Port">Si prega di inserire un numero di porta(0 ~ 65535)</system:String>
	<system:String x:Key="Vailidation.Username">Si prega di inserire un username</system:String>
	<system:String x:Key="Vailidation.Password">Si prega di inserire una password</system:String>

	
	<system:String x:Key="Vailidation.Hint.Volume">etichetta di volume</system:String>
	<system:String x:Key="Vailidation.Hint.Address">host.example.com</system:String>
	<system:String x:Key="Vailidation.Hint.Address.LocalDrive">Cartella</system:String>
	<system:String x:Key="Vailidation.Hint.Username">username</system:String>
	<system:String x:Key="Vailidation.Hint.Password">password</system:String>
	<system:String x:Key="Vailidation.Hint.Port">porta</system:String>
	<system:String x:Key="Vailidation.Hint.Path">path</system:String>
	<system:String x:Key="Vailidation.Hint.Email">id@example.com</system:String>
	<system:String x:Key="Vailidation.Hint.PrivateKeyPath">E' possibile selezionare il file della chiave privata</system:String>

	<system:String x:Key="Button.Yes">Si</system:String>
	<system:String x:Key="Button.No">No</system:String>
	<system:String x:Key="Button.OK">OK</system:String>
	<system:String x:Key="Button.Apply">Applica</system:String>
	<system:String x:Key="Button.Cancel">Cancella</system:String>
	<system:String x:Key="Button.Check">Check</system:String>
	<system:String x:Key="Button.Edit">Modifica</system:String>
	<system:String x:Key="Button.Retry">Riprova</system:String>
	<system:String x:Key="Button.ReAuth">Registrati</system:String>
	<system:String x:Key="Button.Login">Login</system:String>
	<system:String x:Key="Button.SIGNIN">REGISTRATI</system:String>

	<system:String x:Key="ToolTip.Connect">Connettere</system:String>
	<system:String x:Key="ToolTip.Disconnect">Disconnettere</system:String>
	<system:String x:Key="ToolTip.Edit">Modifica</system:String>
	<system:String x:Key="ToolTip.Remove">Rimuovi</system:String>
	<system:String x:Key="ToolTip.NetworkDrive">Drive di rete</system:String>
	<system:String x:Key="ToolTip.SecureProtocol">Secure Protocol</system:String>
	<system:String x:Key="ToolTip.SecureConnection">Secure Connection</system:String>
	<system:String x:Key="ToolTip.Backup">Backup</system:String>

	<system:String x:Key="Message.Title.SelectFolder">Seleziona la cartella</system:String>
	<system:String x:Key="Message.Title.DeleteDrive">Cancella drive</system:String>

	<system:String x:Key="Message.NotSupportNetworkDrive">RaiDrive non supporta un'unità di rete.</system:String>
	<system:String x:Key="Message.NotSupportRaiDrive">RaiDrive non supporta un'unità per connettersi da sola.</system:String>
	<system:String x:Key="Message.Exist">Questa cartella è già inclusa.</system:String>
	<system:String x:Key="Message.SelectedPath">Seleziona Path</system:String>
	<system:String x:Key="Message.DuplicatedPath">Duplica Path</system:String>

	<system:String x:Key="Message.SureDelete">Sei sicuro di voler eliminare in modo permanente &quot;{0} ({1})&quot; ?</system:String>
	<system:String x:Key="Message.Title.ServiceDown">Ripristina RaiDrive</system:String>
	<system:String x:Key="Message.Title.Reconnect">Riconnetti RaiDrive</system:String>
	<system:String x:Key="Message.ServiceDown">Si prega di premere il tasto OK, RaiDrive sarà attivato.</system:String>
	<system:String x:Key="Message.Settings.Reconnect">Si prega di premere il tasto OK, è necessario ricollegare la memoria remota affinché le impostazioni modificate abbiano effetto.</system:String>
	<system:String x:Key="Message.NotReady.Reboot">RaiDrive non è pronto per l'avvio, è necessario riavviare il sistema.</system:String>
	<system:String x:Key="Message.NotReady.Driver">Il driver di dispositivo non è installato sul tuo sistema. È necessario reinstallare RaiDrive.</system:String>
	<system:String x:Key="Message.NotSupport.Browser.Dropbox">Dropbox supporta Internet Explorer 10, 11. È consigliabile installare Internet Explorer 11.</system:String>
	<system:String x:Key="Message.Connect.By">Connesso a RaiDrive</system:String>
	<system:String x:Key="Message.Maximum.Drive">È possibile creare fino a 8 unità nella versione corrente</system:String>
	<system:String x:Key="Message.License.Expired">La tua licenza è scaduta. Devi scaricare la nuova versione. Premere OK per aggiornare.</system:String>
	<system:String x:Key="Message.License.NotReady">RaiDrive non può validare la tua licenza.</system:String>
	<system:String x:Key="Message.UnknownSpace">Spazio sconosciuto</system:String>
	<system:String x:Key="Message.CurrentVersion">La versione corrente è {0}</system:String>
	<system:String x:Key="Message.Cache.Folder.NotSupport">La cartella temporanea deve essere una cartella sull'unità disco locale. L'unità di rete non è supportata.</system:String>

	<system:String x:Key="Message.ErrorRemoteDriveAuth">Autorizzazione o autenticazione fallita. Vorresti autenticarti di nuovo?</system:String>
	<system:String x:Key="Message.ErrorRemoteDriveWantRelogin">Autorizzazione o autenticazione fallita. Vorresti autenticarti di nuovo? (Se continua a fallire, cancella l'unità e ricreala.)</system:String>
	<system:String x:Key="Message.ErrorRemoteDriveLimit">La quota di download è stata superata. Le restrizioni di download sono la politica di  {0}.</system:String>
	<system:String x:Key="Message.ErrorRemoteDriveRemake">Il metodo di connessione alla memoria remota è cambiato.</system:String>
	<system:String x:Key="Message.ErrorCacheDiskFull">Lo spazio di archiviazione della cache non è sufficiente. Faresti meglio ad aumentare lo spazio di archiviazione.</system:String>
	<system:String x:Key="Message.ErrorInternet">Impossibile connettersi alla memoria remota. Per favore controlla la tua connessione Internet e prova di nuovo.</system:String>
	<system:String x:Key="Message.ErrorDiskLetterExist">È necessario modificare la lettera dell'unità o il nome dell'unità.</system:String>

	<system:String x:Key="Message.OAuth.InvalidClient">Dominio non gestito da Active Directory</system:String>
	<system:String x:Key="Message.OAuth.InvalidClientDescription">Il tuo account non è gestito da Active Directory. È necessario contattare Active Directory o l'amministratore di dominio o accedere come account personale.</system:String>

	
	<system:String x:Key="WebExceptionStatus.ConnectFailure">Si prega di controllare l'indirizzo.</system:String>
	<system:String x:Key="WebExceptionStatus.ConnectionClosed">Si prega di ricontrollare il protocollo {0} e la porta {1}.</system:String>
	<system:String x:Key="WebExceptionStatus.SendFailure">Si prega di ricontrollare il protocollo {0} e la porta {1}.</system:String>
	<system:String x:Key="WebExceptionStatus.ReceiveFailure">Si prega di ricontrollare il protocollo {0} e la porta {1}.</system:String>

	<system:String x:Key="HttpStatusCode.MethodNotAllowed">Si prega di verificare se il percorso {0} esiste o se l'accesso è concesso.</system:String>
	<system:String x:Key="HttpStatusCode.Unauthorized">Si prega di verificare se il percorso {0} esiste o se l'accesso è concesso. (password).</system:String>

	<system:String x:Key="SocketError.TimedOut">Si prega di controllare l'indirizzo.</system:String>
	<system:String x:Key="SocketError.ConnectionRefused">Si prega di controllare la porta {0}.</system:String>

	<system:String x:Key="OtherResponseCode.2">Percorso non trovato. Controlla il percorso{0}.</system:String>
	<system:String x:Key="OtherResponseCode.3">Si prega di ricontrollare il protocollo {0} e la porta {1}.</system:String>
	

	<system:String x:Key="Words.Reason">Reason</system:String>
	<system:String x:Key="Words.Delegation.Stop">Delegazione interrotta</system:String>
	<system:String x:Key="Words.Drive">Drive</system:String>
	<system:String x:Key="Words.FreeSpace">Spazion libero</system:String>
	<system:String x:Key="Words.Send.Opinion">Invia opinione</system:String>
	<system:String x:Key="Words.Code">Code</system:String>
	<system:String x:Key="Words.Path">Path</system:String>
	<system:String x:Key="Words.File">File</system:String>
	<system:String x:Key="Words.Ready">Ready</system:String>
	<system:String x:Key="Words.Time">Time</system:String>
	<system:String x:Key="Words.Error">Error</system:String>
	<system:String x:Key="Words.State">Stato</system:String>
	<system:String x:Key="Words.Size">Size</system:String>
	<system:String x:Key="Words.Description">Descrizione</system:String>

	<system:String x:Key="Help.Text">HELP</system:String>
	<system:String x:Key="Help.Add.Drive">HERE WE GO~</system:String>
	<system:String x:Key="Help.ServiceDown">RaiDrive Il servizio è stato interrotto.</system:String>
	<system:String x:Key="Help.ServiceDown.Press">Si prega di premere il pulsante, RaiDrive sarà avviato.</system:String>
	<system:String x:Key="Help.InternetDown">La tua connessione Internet sembra essere disconnessa. Per favore controlla la tua connessione Internet.</system:String>
	<system:String x:Key="Help.InternetDown.RetryAfter">Riprova dopo {0} secondi(s).</system:String>
	<system:String x:Key="Help.License.ForBusiness">per la versione commerciale</system:String>

	<system:String x:Key="Upgrade">Upgrade</system:String>
	<system:String x:Key="Upgrade.Uptodate">Stai utilizzando l'ultima versione</system:String>
	<system:String x:Key="Upgrade.NewVersion">È possibile eseguire l'aggiornamento alla versione {0}</system:String>
	<system:String x:Key="Upgrade.New">È possibile eseguire l'aggiornamento alla nuova versione</system:String>

	<system:String x:Key="NotifyIcon.Open">Apri RaiDrive</system:String>
	<system:String x:Key="NotifyIcon.CheckUpdate">Controlla aggiornamenti</system:String>
	<system:String x:Key="NotifyIcon.Exit">Uscita</system:String>
	<system:String x:Key="NotifyIcon.Exit.Message">Sei sicuro di voler disconnettere tutte le connessioni prima di uscire?</system:String>

	<system:String x:Key="State.Space.Format">{0} liberi di {1} {2}</system:String>
	<system:String x:Key="State.Space.Used">usato</system:String>

	<system:String x:Key="Brand.Synology">Synology</system:String>
	<system:String x:Key="Brand.QNAP">QNAP</system:String>
	<system:String x:Key="Brand.Box_com">Box</system:String>
	<system:String x:Key="Brand.ipTIME">ipTIME</system:String>
	<system:String x:Key="Brand.WD">WD</system:String>
	<system:String x:Key="Brand.etc">etc</system:String>

	
	<system:String x:Key="Backup">Backup</system:String>
	<system:String x:Key="Backup.Add">Aggiungi</system:String>
	<system:String x:Key="Backup.Delete">Cancella</system:String>
	<system:String x:Key="Backup.Start">Avvio</system:String>
	<system:String x:Key="Backup.Stop">Stop</system:String>
	<system:String x:Key="Backup.BackupNOW">Backup ORA</system:String>
	<system:String x:Key="Backup.NOW">ORA</system:String>
	<system:String x:Key="Backup.Save">Salva</system:String>
	<system:String x:Key="Backup.ClearLog">Pulisci log</system:String>
	<system:String x:Key="Backup.DestRootFolder">Cartella remota</system:String>
	<system:String x:Key="Backup.SourceFolders">Cartella di origine</system:String>
	<system:String x:Key="Backup.Progress">Progress</system:String>
	<system:String x:Key="Backup.AutoStart">Auto avvio</system:String>
	<system:String x:Key="Backup.LogTab.Current">Corrente</system:String>
	<system:String x:Key="Backup.LogTab.All">Tutti</system:String>
	<system:String x:Key="Backup.LogTab.Error">Errore</system:String>
	<system:String x:Key="Backup.LogTab.Ready">Pronto</system:String>
	<system:String x:Key="Backup.LogTab.Left">Left</system:String>
	<system:String x:Key="Backup.LogTab.File">File</system:String>
	<system:String x:Key="Backup.LogTab.Folder">Cartella</system:String>
	<system:String x:Key="Backup.LogTab.FollowLatest">Segui l'ultimo</system:String>
	<system:String x:Key="Backup.Count.Left">Left</system:String>
	<system:String x:Key="Backup.Count.Processed">Processed</system:String>

	<system:String x:Key="Message.Backup.BackupTargetFolder">Seleziona una cartella remota in cui verranno archiviati i file</system:String>

</ResourceDictionary>
`

**Comment by Stanly5** [comment]
@gabrig11 
Thank you so much for your contribution! It's great helps for us.
To keep who is contributor, "Pull Request" is preferred. If you are ok, then please download below "StringDictionary.it.zip" file which is made by your translation above, and unzip. And then upload and issue pull request.

[StringDictionary.it.zip](https://github.com/RaiDrive/Translation/files/2602061/StringDictionary.it.zip)

If you are not familiar with pull request process, then please refer to below.

- At first, in RaiDrive/Translation repository, click "Fork" which is upper right. It makes the clone of RaiDrive/Translation in your page.
- In your **gabrig11**/translation repository, choose "<>Code" tab. (upper left)
- You can find and Click "Upload files" right upper
- Upload the file with dragging your unziped local "StringDictionary.it.xaml" file to the area, writing comments on the box just below "Commit changes", and then press the green "Commit changes" button.
- You can confirm everything is well on StringDictionary.it.xaml with click the file.
- For the pull request, choose"Pull requests" tab (just right side of <>Code), and press the green "New pull request" button.
- GitHub automatically checks what's the difference, and will show 1 changed file which is StringDictionary.it.xaml. Please double check base fork:RaiDrive/Translation master, <- head fork: gabrig11/translation master. And then press the green "Create pull request".
- Writing the title and comments, and then press the green "Create pull request" button.

After above step, I can get your pull request, and after merge your pull request, it will be applied main file on RaiDrive Translation repository, and you are registered on our contributors.

If you don't want to follow it up, then I can upload it as well instead of you. But in this case we could not keep the log you are the Contributor.

Anyhow thank you so much for your helps again!

**Comment by Stanly5** [comment]
@gabrig11
Hello~
I'm waiting your response about "Pull Request". If it is bothering you, then I can make pull request by myself, but in this case please recognize your great contribution cannot be recorded.
If there is no feedback, then I would do it after some more days.
Anyhow I would like to give you my thank for your contribution again.

**Comment by Stanly5** [comment]
@gabrig11 
Due to the no response from you, I uploaded it.
However if you would like to record your contribution, please create pull request with small change.
