### ISSUE TITLE
Malay (ms-MY) Translation

### ISSUE THREAD

**Issue by molokal** [RaiDrive/Translation#54]
Hi,

I've completed and pulled request for Malay translation.
Hope it helps.
[https://github.com/RaiDrive/Translation/pull/53](https://github.com/RaiDrive/Translation/pull/53)

**Comment by Stanly5** [comment]
Hello Molokai,

Thank you so much for your helps. It is merged.
Please keep seeing RaiDrive and have a great day!

**Comment by molokal** [comment]
You're welcome!
