### ISSUE TITLE
can RaiDrive mount a cloud drive to a local drive like NetDrive do?

### ISSUE THREAD

**Issue by elfive** [RaiDrive/Translation#55]
first of all, thank you guys, you did a great job!
but......
NetDrive can mount a cloud drive to a local disk drive, can you guys add a feature like this?
now RaiDrive 1.4.4 can only mount to a net disk drive, sometimes it's not so friendly to use in other apps.

**Comment by Stanly5** [comment]
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
