### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by yhy4521** [RaiDrive/Translation#56]
1，非常感谢贵团队做了这么好的软件，而且还免费，希望您继续坚持下去

2，在设置过程中，波折太多，最主要的问题是.net 4.6.2好多机器都不能安装，不可知的错误，我至少试验了4台机器，只有一台可以顺利安装

3，发现一个错误，安装的时候默认是C：盘，我习惯安装到d盘，但安装完毕以后，发现，文件是不可用的，查看了“RaiDrive”图标的属性，发现默认的指向还是Ç盘

来自microman（work@gjgtm.com）
中国

**Comment by Stanly5** [comment]
@yhy4521 
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
