### ISSUE TITLE
登陆失败：ErrorRemoteDriveAuth(103)

### ISSUE THREAD

**Issue by Tespera** [RaiDrive/Translation#59]
![qq 20181205083628](https://user-images.githubusercontent.com/27461964/49500832-8b4ddf80-f8ac-11e8-988d-10aaa68f4e33.png)

**Comment by Stanly5** [comment]
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
