### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bitfabrikken** [RaiDrive/Translation#60]
Thanks for some great software! :)

**Here's a few things that would be nice to have:**
* Option to select auto drive letter assignment. I would prefer it to mount from last to first, e.g. mounting to Z over Y, etc. If Z, Y, X are taken, it should take W.
* Ability to copy a drive's information / clone it. Not the files on the drive, but the "bookmark" in RaiDrive. Makes it easier to setup a lot of sites, based on the information of another site.

**Comment by Stanly5** [comment]
@bitfabrikken
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day

**Comment by bitfabrikken** [comment]
No problem, just though it was the right place :) Have a great day too.
