### ISSUE TITLE
create backup

### ISSUE THREAD

**Issue by MakuSensei** [RaiDrive/Translation#68]
hello I want to create a read-only access for several accounts and privately share access

**Comment by Stanly5** [comment]
@MakuSensei
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
