### ISSUE TITLE
Released RaiDrive 1.5.0

### ISSUE THREAD

**Issue by Stanly5** [RaiDrive/Translation#71]
RaiDrive 1.5.0 has released in January 18th, 2019. Some additional languages are added and updated.
https://www.raidrive.com/download

**Comment by graphixillusion** [comment]
Hi there.  Is it possible to create a junction or symlink to the raidrive drive and then share the created link? I already tried but if i make a junction i will get this error:
"data present in the reparse point buffer is invalid"
With the symlink, the share is created successfully: if i browse locally it works but when i try to access it from another location i get

"Access Denied" error.

I already tried with another dir (local dir) and symlinks and i'm able to access it through network shares. Any idea to make it works with raidrive? Thank you!

**Comment by Stanly5** [comment]
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
