### ISSUE TITLE
Cant connect to FileRun Server

### ISSUE THREAD

**Issue by M4rt1n17** [RaiDrive/Translation#72]
FileRun is using WebDav
https://sub.domain.tld/dav.php:443

But in RaiDrive its impossible to inser anything after the domain.
This makes this Programm useless if you wanna connect to FileRun Servers.

Would be cool if we can append any other string (like "/dav.php/") to the domain.

**Comment by Stanly5** [comment]
@M4rt1n17
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
