### ISSUE TITLE
proxy configuration

### ISSUE THREAD

**Issue by danportu** [RaiDrive/Translation#73]
system: windows 7 32bits
account: onedrive 

when i set proxy configuration, works fine. but if you close raidrive or reboot computer, it don't connect again, then you must change proxy settings and set again to work fine.

thanks in advance

**Comment by Stanly5** [comment]
@danportu
Hello~
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day

**Comment by danportu** [comment]
thanks

**Comment by Stanly5** [comment]
Always welcome~
