### ISSUE TITLE
Multiple onedrives

### ISSUE THREAD

**Issue by bgougent** [RaiDrive/Translation#76]
When using more than one one-drive with different credentials, only one login is kept. Need to login for other account(s).

With google-drive no problems.

**Comment by Stanly5** [comment]
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
