### ISSUE TITLE
French

### ISSUE THREAD

**Issue by therealcorwin** [RaiDrive/Translation#77]
Hello Team :)

If you want, i can try to help you to translate RaiDrive in French. 

Why don't you use a platform like https://crowdin.com/ (or another), to translate your App ?

Best regards :)

**Comment by Stanly5** [comment]
@therealcorwin
Hello~
Yes, please. If you can give us helps for French, greatly appreciated.
Regarding the using translation platform, we will discuss.
Thank you so much.
Have a great day~
