### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by JeromeFa** [RaiDrive/Translation#78]
Hello,

This is my translations in french for Raidrive
[tradFR.zip](https://github.com/RaiDrive/Translation/files/2893036/tradFR.zip)

**Comment by Stanly5** [comment]
@JeromeFa 
Thank you so much for your contribution!
I can upload your translation. However I'd like to recommend you  to use Pull Request process to be recorded your contribution here. If you would like to do it, please refer to below instruction and follow it up.

* At first, in RaiDrive/Translation repository, click "Fork" which is upper right. It makes the clone of RaiDrive/Translation in your page.
* In your **JeromeFa**/translation repository, choose "<>Code" tab. (upper left)
* You can find and Click "Upload files" right upper
* Upload the file with dragging your unziped local re-named "StringDictionary.fr.xaml" file to the area, writing comments on the box just below "Commit changes", and then press the green "Commit changes" button.
* You can confirm everything is well on StringDictionary.fr.xaml with click the file.
* For the pull request, choose"Pull requests" tab (just right side of <>Code), and press the green "New pull request" button.
* GitHub automatically checks what's the difference, and will show 1 changed file which is StringDictionary.fr.xaml. Please double check base fork:RaiDrive/Translation master, <- head fork: JeromeFa/translation master. And then press the green "Create pull request".
* Writing the title and comments, and then press the green "Create pull request" button.

If you have any question, please leave a message.
Thanks again and have a great day~

**Comment by JeromeFa** [comment]
Done, hope it's OK ;)

**Comment by Stanly5** [comment]
Wonderful!
Thank you so much for your contribution!
Have a great weekend~ 
:-)
