### ISSUE TITLE
Unknown space capacity

### ISSUE THREAD

**Issue by demonclan** [RaiDrive/Translation#84]
![2019-03-04_110110](https://user-images.githubusercontent.com/6886218/53708173-1e2af580-3e6d-11e9-8e1e-2217464bb78b.jpg)

The server is Synology，Is there any way to solve it?

**Comment by Stanly5** [comment]
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
