### ISSUE TITLE
Unable to delete via OneDrive

### ISSUE THREAD

**Issue by Farandinio** [RaiDrive/Translation#85]
Hello, I've connected up RaiDrive to my OneDrive account. But when I try to delete some files/folders within my OneDrive. 

Windows Explorer will process the deletion, but the files will not actually delete. Would you have any ideas? 

Thanks

**Comment by Stanly5** [comment]
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
