### ISSUE TITLE
ED25519 algorithm needs a plugin

### ISSUE THREAD

**Issue by ChaosZero112** [RaiDrive/Translation#89]
I use ED25519 for my SSH keys, but I'm unable to connect using RaiDrive.

Can't find any documentation on getting this working with RaiDrive.

![Scrrenshot](https://i.imgur.com/G0aUL0F.png)

**Comment by Stanly5** [comment]
Here in Github is only for the translation, technical staff doesn't take care of this.
For the supporting, please leave this message to RaiDrive Web.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~
