### ISSUE TITLE
No issue, wish for MAC IOS

### ISSUE THREAD

**Issue by HeinzWuert** [RaiDrive/Translation#91]
What about a version für Apple. There is nothing realy good working on the freeware market!

**Comment by Stanly5** [comment]
Here RaiDrive/Translation in GitHub is only for the translation of RaiDrive. Proper person who can answer for your inquiry cannot follow it up.
Please leave this message again on RaiDrive webpage.
https://www.raidrive.com/contact/

Thank you~
Have a great day
