### ISSUE TITLE
Raidrive Drops mounts

### ISSUE THREAD

**Issue by RikT** [RaiDrive/Translation#93]
It seems that since the last update raidrive seems to drop its mounts once rdp is closed as I use this app on a remote computer it is vital that this does not occur it happens with ftp and team drive connections here is logfile 
[service.log](https://github.com/RaiDrive/Translation/files/3095355/service.log)

**Comment by Stanly5** [comment]
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive  page to get quick supports.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~
