### ISSUE TITLE
sftp on ubuntu

### ISSUE THREAD

**Issue by romnvll** [RaiDrive/Translation#98]
Hello, 
i'm testing raidrive with scp feature .
I can mount a drive with my personnal folder, but, when i try to create a file or folder, i got this error :

Une erreur inattendue vous empêche de créer le fichier : 
Erreur 0x800704D5

(An unexpected error prevents you from creating the file )

Best regards

![image](https://user-images.githubusercontent.com/1440006/57082667-7a888500-6cf7-11e9-9879-06a37a9df6d5.png)

**Comment by Stanly5** [comment]
RaiDrive/Translation in Github is only for the translation work, so technical person likely cannot see your message. Please leave a message again in RaiDrive page to get quick supports.
https://www.raidrive.com/contact/

Thank you.
Have a nice day~
